### ISSUE TITLE
Cannot use string keys for breakpoints

### ISSUE THREAD

**Issue by LouisMazel** [craigrileyuk/vue3-mq#10]
Hi,

I want to use my own breakpoints like this :

```js
app.use(Vue3Mq, {
  breakpoints: {
    'mob-s': 320,
    'mob-m': 425,
    'mob-l': 576,
    'tab-s': 640,
    'tab-m': 768,
    'tab-l': 992,
    'lap-s': 1024,
    'lap-m': 1280,
    'lap-l': 1366,
    'lap-xl': 1440,
    'lap-2xl': 1680,
    'lap-3xl': 1920,
  }
})
```

It's doesn't works

I use this, it's working fine :

```ts
app.use(Vue3Mq, {
  breakpoints: {
    test: 320,
  }
})
```

Other point : No declarations types availables 😢

**Comment by alexcroox** [comment]
Migrating here from Nuxt 2 vue-mq which allowed me to define my breakpoints to match tailwind's naming:

```
breakpoints: {
        xs: 640,
        sm: 768,
        md: 1024,
        lg: 1280,
        xl: 1536,
        '2xl': 1700
      },
```

`Vue3 Mq: "2xl" is an invalid breakpoint key. Breakpoint keys must start with a letter and contain only alphanumeric characters and underscores. Skipping.`

Is there a technical limitation of Vue 3 that means this is no longer possible?
