### ISSUE TITLE
This relative module was not found:

### ISSUE THREAD

**Issue by tuckerserwadda** [craigrileyuk/vue3-mq#12]
This relative module was not found:

* ./vue3-mq in ./src/main.js, ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/views/Vue3Mq.vue?vue&type=script&lang=js

**Comment by craigrileyuk** [comment]
Can you post your OS, node version, install method (CDN, MJS etc) as well as the code that causes the error.

**Comment by tuckerserwadda** [comment]
am using windows 10 OS, i have node v.14.17.6 and i used the npm installation

**Comment by craigrileyuk** [comment]
> am using windows 10 OS, i have node v.14.17.6 and i used the npm installation

And the code you used to call/install Vue3-mq ?

**Comment by craigrileyuk** [comment]
Closing this since it's likely user error and there has been no response.
