### ISSUE TITLE
No Typescript support

### ISSUE THREAD

**Issue by XylianBaker** [craigrileyuk/vue3-mq#13]
Hi @craigrileyuk,

are there any plans for Typescript support by adding a index.d.ts file?

Thanks for your answer

**Comment by craigrileyuk** [comment]
I don't personally work with Typescript, but I'd be happy to accept a pull request for an index.d.ts file if anyone wants to make one.

**Comment by demiro** [comment]
why is this closed? still no TS support

**Comment by dolsup** [comment]
For busy people:
See https://github.com/craigrileyuk/vue3-mq/issues/4#issuecomment-1130365130
