### ISSUE TITLE
npm docs not up to date

### ISSUE THREAD

**Issue by haffi13** [craigrileyuk/vue3-mq#14]
I can see that you fixed a typo in an import statement in the docs.
The typo is still present in the docs on npmjs.com (https://www.npmjs.com/package/vue3-mq)

**Comment by craigrileyuk** [comment]
Yes. The NPM docs will be updated when I next publish a release, and I'm not going to create a release, and cache bust everyone's dependencies for a single typo halfway through a README on a single site.
