### ISSUE TITLE
Usage with Nuxt 3

### ISSUE THREAD

**Issue by benoitlahoz** [craigrileyuk/vue3-mq#15]
Sorry if this is unrelated to your library itself, but would it be possible to add an example to use it in Nuxt 3?

Thank you!

**Comment by craigrileyuk** [comment]
Good timing, there's a brand new, expanded documentation site now available at [Vue3-Mq.info](https://vue3-mq.info) which has an example for installing the package within a Nuxt3 project (see the SSR installation page).
