### ISSUE TITLE
Additional Media Features

### ISSUE THREAD

**Issue by aronduby** [craigrileyuk/vue3-mq#16]
Would love if this had some of the newer media features. Looking at some designs that are going to be coming my way having the pointer/any-pointer available would be quiet helpful

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#media_features

**Comment by craigrileyuk** [comment]
Thanks for the feedback. Sorry I've only just seen this.

With the flurry of new media queries, I'm investigating allowing people to manually add their own to the config. I think that'd be the best way to cover more obscure queries without bloating the central reactive object too much.

**Comment by craigrileyuk** [comment]
Added to the roadmap
