### ISSUE TITLE
Dynamic breakpoints give undefined error

### ISSUE THREAD

**Issue by amcjen** [craigrileyuk/vue3-mq#17]
On version 3.1.0

When using the `updateBreakpoints` functionality, we get the following error:

```
Vue3 Mq: "undefined" is not a valid preset. Available options are: bootstrap5, bootstrap4, bootstrap3, vuetify, tailwind, devices, wordpress
```

When we update the function call to include the following property: `preset: 'tailwind'`, in addition to the `breakpoints: {...}`, the error disappears.

**Comment by craigrileyuk** [comment]
Closed with edaf27d
