### ISSUE TITLE
page is down

### ISSUE THREAD

**Issue by ntan-wan** [craigrileyuk/vue3-mq#25]
https://vue3-mq.info/  website is down

**Comment by craigrileyuk** [comment]
I need to sort another domain out for it. They jacked the prices up for .info domains from £10 per year to over £30 per year (not introductory offer either).

**Comment by igorstasiuk** [comment]
when web site will come back?

**Comment by craigrileyuk** [comment]
> when web site will come back?

Round about now: https://craigrileyuk.github.io/vue3-mq/
