### ISSUE TITLE
Invalid module specifier in package.json

### ISSUE THREAD

**Issue by oliver-koell** [craigrileyuk/vue3-mq#27]
In the package.json the "module" and the "exports.import" should both point to `./dist/vue3-mq.mjs` instead of to `./dist/vue3-mq.js`. The latter is not in ES module format.

In my case, this leads to problems when bundling with vite to the "system" output format.

**Comment by craigrileyuk** [comment]
This should be resolved in version 4 since the package uses `"type": "module"` which defaults to `.js` for ESM files.

**Comment by craigrileyuk** [comment]
This should be resolved in version 4 since the package uses "type": "module" which defaults to .js for ESM files.
