### ISSUE TITLE
Errors and incorrect breakpoint in Safari on Mac

### ISSUE THREAD

**Issue by mrjose** [craigrileyuk/vue3-mq#3]
Hi,

The package appears to be struggling in Safari on Mac (Safari 13.1 macOS Catalina). 
The following is occurring:

- Error on load:
`TypeError: n.addEventListener is not a function. (In 'n.addEventListener("change",r)',  'n.addEventListener' is undefined)`
- Which is thrown on line 334 in the function sanitiseBreakpoints():
`if (!['string', 'number'].includes(_typeof(bp)) || !bp) throw new Error("Invalid or missing breakpoint key");`
- The reported breakpoint is **SM** no matter what the screen size. The functionality works correctly in Chrome on macOS Catalina.

Many thanks,

Jose

**Comment by Saltibarsciai** [comment]
Same issue @mrjose did you do something to fix it?

**Comment by mrjose** [comment]
@Saltibarsciai It appears to be work now on Safari 14 on macOS Big Sur. Puzzling indeed. It would not surprise me if functionality was "fixed" in the latest version of Safari.

**Comment by Saltibarsciai** [comment]
@mrjose unfortunately I needed more support, so if you are in need of lower versions support on safari take a look at this answer. I made a comment about this for vue 3 and it works, of course it's simple so if you need something more complex you'll have to build it yourself https://forum.vuejs.org/t/vue-issue-when-using-method-to-dinamically-render-a-responsive-nav/60256/2

**Comment by craigrileyuk** [comment]
I believe this is due to their using a deprecated method for subscribing to media query changes. The previous method used to be `m.addListener` whereas the current one is `m.addEventListener`. I transitioned to the new method when rewriting this plugin.

**Comment by Saltibarsciai** [comment]
@craigrileyuk will you fix it on next version?

**Comment by craigrileyuk** [comment]
> @craigrileyuk will you fix it on next version?

Already have. I added a fallback on the v2.3.1 version published a few hours ago.

**Comment by Saltibarsciai** [comment]
@craigrileyuk oh, nice! Did you also investigate https://github.com/craigrileyuk/vue3-mq/issues/1 issue?
