### ISSUE TITLE
Typescript Error: Could not find declaration for module 'vue3-mq'

### ISSUE THREAD

**Issue by iKnowMagic** [craigrileyuk/vue3-mq#4]
Hi Craig,

Many thanks for making the Vue 3 version of Vue MQ available. 

I am getting the following typescript error while importing vue3-mq into the main.ts file in vue 3:

> Could not find a declaration file for module 'vue3-mq'. './node_modules/vue3-mq/dist/index.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/vue3-mq` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue3-mq';`ts(7016)

**Comment by craigrileyuk** [comment]
Sorry, but this version doesn't support typescript and I have no plans for changing it to do so.

**Comment by jadsonlucio** [comment]
I have created vue3-md.d.ts file with the types
`declare module 'vue3-mq' {
  import { DefineComponent } from 'vue'
  type Preset =
    | 'bootstrap5'
    | 'bootstrap4'
    | 'bootstrap3'
    | 'vuetify'
    | 'tailwind'
    | 'devices'
    | 'wordpress'
  interface Breakpoints {
    xs: number
    sm: number
    md: number
    lg: number
    xl: number
    xxl: number
  }
  interface MqState {
    current: keyof Breakpoints
    xs: boolean
    sm: boolean
    smMinus: boolean
    smPlus: boolean
    md: boolean
    mdMinus: boolean
    mdPlus: boolean
    lg: boolean
    lgMinus: boolean
    lgPlus: boolean
    xl: boolean
    xlMinus: boolean
    xlPlus: boolean
    xxl: boolean
    orientation: 'landscape' | 'portrait'
    isLandscape: boolean
    isPortrait: boolean
    theme: 'light' | 'dark'
    isLight: boolean
    isDark: boolean
  }
  export function useMq(): MqState
  export function updateBreakpoints({
    breakpoints,
    preset,
  }: {
    breakpoints: Breakpoints
    preset: Preset
  }): void

  export const availableBreakpoints: Breakpoints
  export const Vue3Mq: {
    install: <T>(
      app: T,
      {
        preset,
        breakpoints,
        defaultBreakpoint,
        defaultOrientation,
        defaultMotion,
        defaultTheme,
      }: {
        preset?: Preset
        breakpoints: Breakpoints
        defaultBreakpoint?: keyof Breakpoints
        defaultOrientation?: MqState['orientation']
        defaultMotion?: string
        defaultTheme?: MqState['theme']
      }
    ) => void
  }
  type Target =
    | 'xs'
    | 'sm'
    | 'sm-'
    | 'sm+'
    | 'md'
    | 'md-'
    | 'md+'
    | 'lg'
    | 'lg-'
    | 'lg+'
    | 'xl'
    | 'xl+'
    | 'xl-'
    | 'xxl'
  export const MqResponsive: DefineComponent<{
    target?: Target
    landscape?: boolean
    portrait?: boolean
    dark?: boolean
    light?: boolean
    inert?: boolean
    motion?: boolean
    tag?: string
    listTag?: string
    group?: boolean
  }>
}
`

**Comment by ohuu** [comment]
why not create a pull request and add this .d.ts to the project?

**Comment by craigrileyuk** [comment]
Because the main reactive object allows for dynamically-set keys meaning this would cause more type errors than it solves.

**Comment by multimokia** [comment]
If this project doesn't support typescript out of the get-go, it might be worth updating the page on npmjs which states that it does.
