### ISSUE TITLE
Console leftover

### ISSUE THREAD

**Issue by sheoak** [craigrileyuk/vue3-mq#5]
I get 2  console leftovers in my app due to vue3-mq:

https://github.com/craigrileyuk/vue3-mq/blob/1887068058ef3566bbcb79ffcf201e1d32b4f376/src/component.js#L21
https://github.com/craigrileyuk/vue3-mq/blob/1887068058ef3566bbcb79ffcf201e1d32b4f376/src/component.js#L74

**Comment by craigrileyuk** [comment]
Fixed in version 2.3.2
